MvcSqlServerWebBackup/Controllers/CnnController.cs
using System;
using System.Linq;
using System.Net;
using System.Web.Mvc;
using MvcSqlServerWebBackup.Models;

namespace MvcSqlServerWebBackup.Controllers
{
    public class CnnController: Controller
    {
        /// <summary>
        /// Настройка соединений
        /// </summary>
        /// <returns></returns>
        public ActionResult Index()
        {
            ViewBag.Message = "Настройка соединений.";
            var data = DbContext.Current.GetServerConnections();
            
            return View(data.Select(s => new ModelConnectionView() { Id = s.Id, Name = s.Name, ServerName = s.ServerName }));
        }

        public ActionResult Edit(string id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            
            var item = id.Equals(Guid.Empty.ToString()) ? new ServerConnection() : DbContext.Current.GetServerConnections().Find(s => s.Id == id);
            if (item == null)
            {
                return HttpNotFound();
            }
            return View(new ModelConnectionViewEdit() { Id = item.Id,
                Name = item.Name,
                Memo = item.Memo,
                ServerName = item.ServerName,
                ConnectionString = item.ConnectionString,
                Password = item.Password,
                Uid = item.Uid,
                IntegratedSecurity = item.IntegratedSecurity
            });
        }
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "Id,Name,Memo,ServerName,ConnectionString,Password,Uid,IntegratedSecurity")] ModelConnectionViewEdit item)
        {
            if (ModelState.IsValid)
            {
                //db.Entry(movie).State = EntityState.Modified;
                //db.SaveChanges();
                var v = item.Id.Equals(Guid.Empty.ToString()) ? null : DbContext.Current.GetServerConnections().Find(s => s.Id == item.Id);
                if (v != null)
                {
                    v.Name = item.Name;
                    v.Memo = item.Memo;
                    v.ServerName = item.ServerName;
                    v.ConnectionString = item.ConnectionString;
                    v.Password = item.Password;
                    v.Uid = item.Uid;
                    v.IntegratedSecurity = item.IntegratedSecurity;
                }
                else
                {
                    v= new ServerConnection();
                    v.Id = item.Id;
                    v.Name = item.Name;
                    v.Memo = item.Memo;
                    v.ServerName = item.ServerName;
                    v.ConnectionString = item.ConnectionString;
                    v.Password = item.Password;
                    v.Uid = item.Uid;
                    v.IntegratedSecurity = item.IntegratedSecurity;
                    if (item.Id.Equals(Guid.Empty.ToString()))
                        v.NewId();
                }
                DbContext.Current.Save(v);
                return RedirectToAction("Index");
            }
            return View(item);
        }
        public ActionResult Details(string id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            var item = DbContext.Current.GetServerConnections().Find(s => s.Id == id);
            
            if (item == null)
            {
                return HttpNotFound();
            }
            return View(new ModelConnectionViewEdit(){Id = item.Id, Memo = item.Memo, ServerName = item.ServerName, Name = item.Name});
        }

        public ActionResult Delete(string id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            var item = DbContext.Current.GetServerConnections().Find(s => s.Id == id);
            if (item == null)
            {
                return HttpNotFound();
            }
            //ViewBag.GenreId = new SelectList(db.Genres, "GenreId", "Name", album.GenreId);
            //ViewBag.ArtistId = new SelectList(db.Artists, "ArtistId", "Name", album.ArtistId);
            return View(new ModelConnectionView() { Id = item.Id, Memo = item.Memo, ServerName = item.ServerName, Name = item.Name });
         }
        
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(string id)
        {
            var item = DbContext.Current.GetServerConnections().Find(s => s.Id == id);
            if (item != null)
            {
                DbContext.Current.Delete(item);
            }
            return RedirectToAction("Index");
        }
    }
}

MvcSqlServerWebBackup/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - SqlServerWebBackup</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
</head>
<body>
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                @Html.ActionLink("SqlServerWebBackup", "Index", "Home", new { area = "" }, new { @class = "navbar-brand" })
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li>@Html.ActionLink("Главная", "Index", "Home")</li>
                    <li class="dropdown">
                        <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">Разделы<span class="caret"></span></a>
                        <ul class="dropdown-menu">
                            <li>@Html.ActionLink("Резервное копирование", "Index", "BackupTask")</li>
                            <li>@Html.ActionLink("Сервера", "Index", "Cnn")</li>
                            <li>@Html.ActionLink("Хранилище", "Index", "CloudDrive")</li>
                            <li role="separator" class="divider"></li>
                            <li>@Html.ActionLink("Настройки", "Config", "Home")</li>
                        </ul>
                    </li>

                    <li>@Html.ActionLink("О проекте", "About", "Home")</li>
                </ul>
            </div>
        </div>
    </div>
    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; @DateTime.Now.Year - SqlServerWebBackup</p>
        </footer>
    </div>

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)
</body>
</html>